<?php
$lang['number']   = 'Sąskaitos numeris';
$lang['date']     = 'Išrašymo data';
$lang['time']     = 'Išrasymo laikas';
$lang['due']      = 'Sumokėti iki';
$lang['to']       = 'Pirkėjas';
$lang['from']     = 'Pardavėjas';
$lang['product']  = 'Produktai';
$lang['qty']      = 'Vnt.';
$lang['price']    = 'Kaina';
$lang['discount'] = 'Nuolaida';
$lang['vat']      = 'PVM';
$lang['total']    = 'Viso';
$lang['page']     = 'Puslapis';
$lang['page_of']  = 'iš';
